In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn import linear_model

In [19]:
df =pd.read_excel('Documents//datasets//housebook.xlsx')

In [20]:
df.head()

town  area   price  township  westwindsor  robbinsville
0  monretown  2600  550000         1            0             0
1  monretown  3000  565000         1            0             0
2  monretown  3200  610000         1            0             0
3  monretown  3600  680000         1            0             0
4  monretown  4000  725000         1            0             0

# getties dummy values

In [22]:
dummies=pd.get_dummies(df.town)

In [23]:
dummies

monretown  robbinsvile  westwinsor
0           1            0           0
1           1            0           0
2           1            0           0
3           1            0           0
4           1            0           0
5           0            0           1
6           0            0           1
7           0            0           1
8           0            0           1
9           0            1           0
10          0            1           0
11          0            1           0
12          0            1           0

# concatinating dummies with df values

In [24]:
merged = pd.concat([df ,dummies])

In [25]:
merged

town    area     price  township  westwindsor  robbinsville  \
0     monretown  2600.0  550000.0       1.0          0.0           0.0   
1     monretown  3000.0  565000.0       1.0          0.0           0.0   
2     monretown  3200.0  610000.0       1.0          0.0           0.0   
3     monretown  3600.0  680000.0       1.0          0.0           0.0   
4     monretown  4000.0  725000.0       1.0          0.0           0.0   
5    westwinsor  2600.0  585000.0       0.0          1.0           0.0   
6    westwinsor  2800.0  615000.0       0.0          1.0           0.0   
7    westwinsor  3300.0  650000.0       0.0          1.0           0.0   
8    westwinsor  3600.0  710000.0       0.0          1.0           0.0   
9   robbinsvile  2600.0  575000.0       0.0          0.0           0.0   
10  robbinsvile  2900.0  600000.0       0.0          0.0           0.0   
11  robbinsvile  3100.0  620000.0       0.0          0.0           1.0   
12  robbinsvile  3400.0  695000.0       0.0          0.0           1.0   
0           NaN     NaN       NaN       NaN          NaN           NaN   
1           NaN     NaN       NaN       NaN          NaN           NaN   
2           NaN     NaN       NaN       NaN          NaN           NaN   
3           NaN     NaN       NaN       NaN          NaN           NaN   
4           NaN     NaN       NaN       NaN          NaN           NaN   
5           NaN     NaN       NaN       NaN          NaN           NaN   
6           NaN     NaN       NaN       NaN          NaN           NaN   
7           NaN     NaN       NaN       NaN          NaN           NaN   
8           NaN     NaN       NaN       NaN          NaN           NaN   
9           NaN     NaN       NaN       NaN          NaN           NaN   
10          NaN     NaN       NaN       NaN          NaN           NaN   
11          NaN     NaN       NaN       NaN          NaN           NaN   
12          NaN     NaN       NaN       NaN          NaN           NaN   

    monretown  robbinsvile  westwinsor  
0         NaN          NaN         NaN  
1         NaN          NaN         NaN  
2         NaN          NaN         NaN  
3         NaN          NaN         NaN  
4         NaN          NaN         NaN  
5         NaN          NaN         NaN  
6         NaN          NaN         NaN  
7         NaN          NaN         NaN  
8         NaN          NaN         NaN  
9         NaN          NaN         NaN  
10        NaN          NaN         NaN  
11        NaN          NaN         NaN  
12        NaN          NaN         NaN  
0         1.0          0.0         0.0  
1         1.0          0.0         0.0  
2         1.0          0.0         0.0  
3         1.0          0.0         0.0  
4         1.0          0.0         0.0  
5         0.0          0.0         1.0  
6         0.0          0.0         1.0  
7         0.0          0.0         1.0  
8         0.0          0.0         1.0  
9         0.0          1.0         0.0  
10        0.0          1.0         0.0  
11        0.0          1.0         0.0  
12        0.0          1.0         0.0

In [26]:
merged = pd.concat([df ,dummies] ,axis='columns')

In [27]:
merged

town  area   price  township  westwindsor  robbinsville  monretown  \
0     monretown  2600  550000         1            0             0          1   
1     monretown  3000  565000         1            0             0          1   
2     monretown  3200  610000         1            0             0          1   
3     monretown  3600  680000         1            0             0          1   
4     monretown  4000  725000         1            0             0          1   
5    westwinsor  2600  585000         0            1             0          0   
6    westwinsor  2800  615000         0            1             0          0   
7    westwinsor  3300  650000         0            1             0          0   
8    westwinsor  3600  710000         0            1             0          0   
9   robbinsvile  2600  575000         0            0             0          0   
10  robbinsvile  2900  600000         0            0             0          0   
11  robbinsvile  3100  620000         0            0             1          0   
12  robbinsvile  3400  695000         0            0             1          0   

    robbinsvile  westwinsor  
0             0           0  
1             0           0  
2             0           0  
3             0           0  
4             0           0  
5             0           1  
6             0           1  
7             0           1  
8             0           1  
9             1           0  
10            1           0  
11            1           0  
12            1           0

# dropping columns

In [29]:
final=merged.drop(['town' ,'westwindsor'],axis="columns")

In [30]:
final

area   price  township  robbinsville  monretown  robbinsvile  westwinsor
0   2600  550000         1             0          1            0           0
1   3000  565000         1             0          1            0           0
2   3200  610000         1             0          1            0           0
3   3600  680000         1             0          1            0           0
4   4000  725000         1             0          1            0           0
5   2600  585000         0             0          0            0           1
6   2800  615000         0             0          0            0           1
7   3300  650000         0             0          0            0           1
8   3600  710000         0             0          0            0           1
9   2600  575000         0             0          0            1           0
10  2900  600000         0             0          0            1           0
11  3100  620000         0             1          0            1           0
12  3400  695000         0             1          0            1           0

# developing linear model

In [31]:
reg = linear_model.LinearRegression()

# choosing and dropping  data for modeling

In [33]:
x = final.drop('price' ,axis="columns")

In [34]:
x

area  township  robbinsville  monretown  robbinsvile  westwinsor
0   2600         1             0          1            0           0
1   3000         1             0          1            0           0
2   3200         1             0          1            0           0
3   3600         1             0          1            0           0
4   4000         1             0          1            0           0
5   2600         0             0          0            0           1
6   2800         0             0          0            0           1
7   3300         0             0          0            0           1
8   3600         0             0          0            0           1
9   2600         0             0          0            1           0
10  2900         0             0          0            1           0
11  3100         0             1          0            1           0
12  3400         0             1          0            1           0

# dependent variable 

In [35]:
y =final.price

In [36]:
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

# training and fitting data

In [37]:
reg.fit(x,y)

LinearRegression()

# predicting prices

In [40]:
reg.predict([[2800 ,1 ,0,1,0,0]]) # each parameter represent row of each table except price

array([563476.53142406])

In [42]:
reg.predict([[3700 ,0 ,1,0,1,0]])


array([716115.75178991])

# acuracy of the model

In [44]:
reg.score(x,y)*100

94.34313578746801

# using skearn preprocessing

In [47]:
from sklearn.preprocessing import LabelEncoder

In [48]:
le =LabelEncoder()

In [49]:
df

town  area   price  township  westwindsor  robbinsville
0     monretown  2600  550000         1            0             0
1     monretown  3000  565000         1            0             0
2     monretown  3200  610000         1            0             0
3     monretown  3600  680000         1            0             0
4     monretown  4000  725000         1            0             0
5    westwinsor  2600  585000         0            1             0
6    westwinsor  2800  615000         0            1             0
7    westwinsor  3300  650000         0            1             0
8    westwinsor  3600  710000         0            1             0
9   robbinsvile  2600  575000         0            0             0
10  robbinsvile  2900  600000         0            0             0
11  robbinsvile  3100  620000         0            0             1
12  robbinsvile  3400  695000         0            0             1

# fitting transform - taking dataframe as the import 

In [51]:
dfile = df
le.fit_transform(dfile.town)

array([0, 0, 0, 0, 0, 2, 2, 2, 2, 1, 1, 1, 1])

In [52]:
df.town =le.fit_transform(dfile.town)

In [54]:
df.town

0     0
1     0
2     0
3     0
4     0
5     2
6     2
7     2
8     2
9     1
10    1
11    1
12    1
Name: town, dtype: int64

# label encoded

In [55]:
dfile

town  area   price  township  westwindsor  robbinsville
0      0  2600  550000         1            0             0
1      0  3000  565000         1            0             0
2      0  3200  610000         1            0             0
3      0  3600  680000         1            0             0
4      0  4000  725000         1            0             0
5      2  2600  585000         0            1             0
6      2  2800  615000         0            1             0
7      2  3300  650000         0            1             0
8      2  3600  710000         0            1             0
9      1  2600  575000         0            0             0
10     1  2900  600000         0            0             0
11     1  3100  620000         0            0             1
12     1  3400  695000         0            0             1

# independent variables

In [59]:
x =dfile[['town' ,'area']].values

In [60]:
x

array([[   0, 2600],
       [   0, 3000],
       [   0, 3200],
       [   0, 3600],
       [   0, 4000],
       [   2, 2600],
       [   2, 2800],
       [   2, 3300],
       [   2, 3600],
       [   1, 2600],
       [   1, 2900],
       [   1, 3100],
       [   1, 3400]])

# dependent variables

In [61]:
y = dfile.price

In [62]:
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

# import one hot encoder

In [67]:
from sklearn.preprocessing import OneHotEncoder
onehot = OneHotEncoder() # categorical features should 0 position

# fitting transform and converting it to array

In [69]:
x=onehot.fit_transform(x).toarray()

In [70]:
x

array([[1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]])

# dropping(skipping) the first column and fetting all row data 

In [72]:
x=x[:, 1:]
x

array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]])

# fitting the model

In [73]:
reg.fit(x,y)

LinearRegression()

# making prediction

In [76]:
reg.predict([[2000,1,1,0,0,0,1,1,1,0,1,0]])

array([48116749.99999996])

# testing the acuracy of the model

In [78]:
reg.score(x,y) * 100

99.9843131576407

# writing into csv file

In [79]:
df.to_csv('Documents//datasets//online_house_price.csv')

In [80]:
pwd

'/Users/apple'