In [77]:
import pandas as pd
from sklearn import svm ,datasets

iris = datasets.load_iris()

In [78]:
df = pd.DataFrame(iris.data,columns=iris.feature_names)
df['flower'] =iris.target


In [79]:
df['flower']=df['flower'].apply(lambda x :iris.target_names[x])

In [80]:
df[47:52]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
47                4.6               3.2                1.4               0.2   
48                5.3               3.7                1.5               0.2   
49                5.0               3.3                1.4               0.2   
50                7.0               3.2                4.7               1.4   
51                6.4               3.2                4.5               1.5   

        flower  
47      setosa  
48      setosa  
49      setosa  
50  versicolor  
51  versicolor

In [81]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(iris.data ,iris.target,test_size=0.3)

In [82]:
model = svm.SVC(kernel='rbf' ,C=30 ,gamma='auto')
model.fit(x_train,y_train)
model.score(x_test,y_test)

1.0

# different scores for with parameters

In [83]:
from sklearn.model_selection import cross_val_score

In [84]:
cross_val_score(svm.SVC(kernel='rbf' ,C=10 ,gamma='auto'), iris.data ,iris.target,cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

# linear parameter

In [85]:
cross_val_score(svm.SVC(kernel='linear' ,C=10 ,gamma='auto'), iris.data ,iris.target,cv=5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [86]:
cross_val_score(svm.SVC(kernel='rbf' ,C=20 ,gamma='auto'), iris.data ,iris.target,cv=5)

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

# using for loop to achieve the above work

In [87]:
import numpy as np
kernels =['rbf' ,'linear']
c =[1,10,20]
avg_score ={}
for kval in kernels:
    for cval in c:
        sv_score =cross_val_score(svm.SVC(kernel=kval ,C=cval ,gamma='auto'), iris.data ,iris.target,cv=5)
        avg_score[kval + ' _ ' ,str(cval)] = np.average(sv_score) 

avg_score        

{('rbf _ ', '1'): 0.9800000000000001,
 ('rbf _ ', '10'): 0.9800000000000001,
 ('rbf _ ', '20'): 0.9666666666666668,
 ('linear _ ', '1'): 0.9800000000000001,
 ('linear _ ', '10'): 0.9733333333333334,
 ('linear _ ', '20'): 0.9666666666666666}

# using GrisearchCV 

In [88]:
from sklearn.model_selection import GridSearchCV

In [89]:
clf =GridSearchCV(svm.SVC(gamma='auto'),{'C':[1,10,20] ,'kernel':['rbf','linear']} ,cv=5 ,return_train_score=False)

In [90]:
clf.fit(iris.data ,iris.target)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20], 'kernel': ['rbf', 'linear']})

In [91]:
clf.cv_results_

{'mean_fit_time': array([0.00111427, 0.00076032, 0.00091233, 0.00079532, 0.0014442 ,
        0.00088077]),
 'std_fit_time': array([1.60698268e-04, 1.65641932e-04, 6.00035859e-05, 1.77163544e-04,
        4.52308677e-04, 8.17268008e-05]),
 'mean_score_time': array([0.0009346 , 0.0005147 , 0.00061135, 0.00046959, 0.0010088 ,
        0.00070462]),
 'std_score_time': array([4.40226875e-04, 9.95136872e-05, 6.46975777e-05, 9.76680305e-05,
        5.00685565e-04, 3.06581063e-04]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'ker

# using dataframe

In [92]:
df= pd.DataFrame(clf.cv_results_)

In [93]:
df.head()

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.001114      0.000161         0.000935        0.000440       1   
1       0.000760      0.000166         0.000515        0.000100       1   
2       0.000912      0.000060         0.000611        0.000065      10   
3       0.000795      0.000177         0.000470        0.000098      10   
4       0.001444      0.000452         0.001009        0.000501      20   

  param_kernel                         params  split0_test_score  \
0          rbf      {'C': 1, 'kernel': 'rbf'}           0.966667   
1       linear   {'C': 1, 'kernel': 'linear'}           0.966667   
2          rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
3       linear  {'C': 10, 'kernel': 'linear'}           1.000000   
4          rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0           0.966667           0.966667                1.0   
1                1.0           0.966667           0.966667                1.0   
2                1.0           0.966667           0.966667                1.0   
3                1.0           0.900000           0.966667                1.0   
4                1.0           0.900000           0.966667                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.980000        0.016330                1  
1         0.980000        0.016330                1  
2         0.980000        0.016330                1  
3         0.973333        0.038873                4  
4         0.966667        0.036515                5

In [94]:
df[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0       1          rbf         0.980000
1       1       linear         0.980000
2      10          rbf         0.980000
3      10       linear         0.973333
4      20          rbf         0.966667
5      20       linear         0.966667

In [95]:
dir(clf)

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_check_is_fitted',
 '_check_n_features',
 '_estimator_type',
 '_format_results',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_pairwise',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_required_parameters',
 '_run_search',
 '_validate_data',
 'best_estimator_',
 'best_index_',
 'best_params_',
 'best_score_',
 'classes_',
 'cv',
 'cv_results_',
 'decision_function',
 'error_score',
 'estimator',
 'fit',
 'get_params',
 'iid',
 'inverse_transform',
 'multimetric_',
 'n_features_in_',
 'n_jobs',
 'n_splits_',
 'param_grid',
 'pre_

In [96]:
clf.best_score_

0.9800000000000001

In [97]:
clf.best_params_

{'C': 1, 'kernel': 'rbf'}

# using RandomizedSearchcv

In [98]:
from sklearn.model_selection import RandomizedSearchCV

In [99]:
rs =RandomizedSearchCV(svm.SVC(gamma='auto'),{'C':[1,10,20],'kernel':['rbf','linear']},cv=5,
                      return_train_score=False, n_iter=2)

In [100]:
rs.fit(iris.data,iris.target)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=2,
                   param_distributions={'C': [1, 10, 20],
                                        'kernel': ['rbf', 'linear']})

In [101]:
pd.DataFrame(rs.cv_results_)[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0       1       linear         0.980000
1      20          rbf         0.966667

# assessing the best model to use

In [102]:
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [103]:
model_params={
    'svm':{'model':svm.SVC(gamma='auto'),'params':{'C':[1,10,20],'kernel':['rbf','linear']}},
    'random_forest':{'model':RandomForestClassifier(),'params':{'n_estimators':[1,5,10]}},
    'logistic_regression':{'model':LogisticRegression(solver='liblinear',multi_class='auto'),'params':{'C':[1,5,10]}}
}

In [104]:
scores=[]
for model_name,mp in model_params.items():
    clf =GridSearchCV(mp['model'],mp['params'],cv=5,return_train_score=False)
    clf.fit(iris.data,iris.target)
    scores.append({'model':model_name,'best_score':clf.best_score_,'best_params':clf.best_params_})

In [105]:
df =pd.DataFrame(scores,columns=['model','best_score','best_params'])

In [106]:
df

model  best_score                best_params
0                  svm    0.980000  {'C': 1, 'kernel': 'rbf'}
1        random_forest    0.960000        {'n_estimators': 5}
2  logistic_regression    0.966667                   {'C': 5}